# Generated by Django 3.2.24 on 2024-03-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20240320_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_inventory',
            name='Unit_Of_Product',
            field=models.CharField(default='Gram', max_length=200),
            preserve_default=False,
        ),
    ]
