# Generated by Django 3.2.24 on 2024-03-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_rename_unit_of_product_add_inventory_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_inventory',
            old_name='name',
            new_name='Month',
        ),
        migrations.AddField(
            model_name='create_inventory',
            name='Year',
            field=models.CharField(default=2021, max_length=200),
            preserve_default=False,
        ),
    ]
